using System;

namespace ResurrectionRP_Server.Models.InventoryData
{
    public enum ItemID : Int64
    {
        Fromage = 1,
        Pain = 2,
        Canne = 3,
        Sardine = 4,
        GrappeRaisin = 5,
        Raisin = 6,
        MineraiCuivre = 7,
        Cuivre = 8,
        Sable = 9,
        Bouteille = 10,
        Vine = 11,
        RondinDeBois = 12,
        PlancheBois = 13,
        Jerrycan = 14,
        JambonBeurre = 15,
        Poulet = 16,
        Water = 17,
        Coffee = 18,
        Donuts = 19,
        Sprunk = 20,
        Ecola = 21,
        Bandages = 22,
        KitSoin = 23,
        Defibrilateur = 24,
        Radio = 25,
        IdentityCard = 26,
        Taser = 27,
        Matraque = 28,
        LampeTorche = 29,
        HeavyPistol = 30,
        Carabine = 31,
        Pump = 32,
        Handcuff = 33,
        Phone = 34,
        Mask = 35,
        Nems = 36,
        Nouille = 37,
        Knife = 38,
        Hammer = 39,
        Bat = 40,
        Crowbar = 41,
        GolfClub = 42,
        Bottle = 43,
        Daggar = 44,
        KnuckleDuster = 45,
        Machete = 46,
        Flashlight = 47,
        SwitchBlade = 48,
        PoolCue = 49,
        Wrench = 50,
        BattleAxe = 51,
        Musket = 52,
        //Benny's
        Moteur1 = 53,
        Moteur2 = 54,
        Moteur3 = 55,
        Moteur4 = 56,
        FreinRue = 57,
        FreinSport = 58,
        FreinCourse = 59,
        TransRue = 60,
        TransSport = 61,
        TransCourse = 62,
        SuspRabaisse = 63,
        SuspRue = 64,
        SusSport = 65,
        SusCourse = 66,
        Turbo = 67,
        Esthetique = 68,
        Pistol = 69,
        Ramen = 70,
        Sushi = 71,
        Takoyaki = 72,
        Champagne = 73,
        Sake = 74,
        GSauvetage = 75,
        Grappa = 76,
        Lasagnes = 77,
        Pizza = 78,
        Vodka = 79,
        Caviar = 80,
        Syrniki = 81,
        Fricadelle = 82,
        HotDog = 83,
        Whisky = 84,
        Gnole = 85,
        Biere = 86,
        Chocolat = 87,
        Tequila = 88,
        Tacos = 89,
        RagoutRenard = 90,
        BrochetteEcureuil = 91,
        Mirabelle = 93,
        CombatPistol = 94,
        Colt1911 = 95,
        Colt6Coup = 96,
        Magnum357 = 97,
        DoubleBarrelShotgun = 98,
        Pistol50 = 99,
        SNSPistol = 100,
        CrateTool = 101,
        BouteilleTraite = 102,
        PetrolBrute = 103,
        Petrol = 104,
        Cloth = 105,
        Bag = 106,
        Plastic = 107,
        Apple = 108,
        MineraiFer = 109,
        Fer = 110,
        PepiteOr = 111,
        Pioche = 112,
        Key = 113,
        Hache = 114,
        Building = 115,
        GSkunk = 116,
        GPurple = 117,
        GOrange = 118,
        GWhite = 119,
        Hydro = 120,
        Secateur = 121,
        BSkunk = 122,
        BPurple = 123,
        BOrange = 124,
        BWhiteWidow = 125,
        CharbonBrute = 126,
        CharbonTraite = 127,
        TShirt = 128,
        Shoes,
        Jacket,
        Glasses,
        Hats,
        Necklace,
        Ears,
        Watch,
        Bracelet,
        Pant,
        Glove,
        Kevlar,
        AppleJuice,
        Weapon,
        GrapeJuice,
        Canneasurcre,
        RhumLiquide,
        BouquetFleur,
        Bague,
        LockPick,
        Serflex,

        MarteauPiqueur,
        Marteau,

        CuivreFondu,
        DetecteurMetaux,
        LingotOr,
        SacArgent,
        Pelle,
        Seau,
        Soufflet,
        OutilCouteau,
        OutilMachette,

        Melasse,
        MelasseApple,
        MelasseRaisin,

        Rhum,
        RhumApple,
        RhumRaisin

    }
}
